[project]
name = "es2-ap5"
version = "0.1.0"
description = ""
authors = [
    {name = "Gustavo Amaral Bernardino",email = "gu.amaralb@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = []


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
pytest-cov = "^7.0"
taskipy = "^1.14"
ruff = "^0.14"


[tool.taskipy.tasks]
lint = 'ruff check'
pre_format = 'ruff check --fix'
format = 'ruff format'
pre_run = 'task format'
run = 'python -m es2_ap5.cli'
pre_test = 'task lint'
test = 'pytest -s -x --cov=es2_ap5 -vv'
post_test = 'coverage html'


[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'


[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'
